server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: user-web
          uri: lb://USER-WEB
          predicates:
            - Path=/user/**,/res/**
        - id: friend-web
          uri: lb://WECHAT-FRIEND
          predicates:
            - Path=/friendApply/**,/friend/**
  application:
    name: wechat-gateway