server:
  port: 8085
spring:
  application:
    name: user-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://139.9.53.186:3306/wechat

fdfs:
  connect-timeout: 10000
  tracker-list:
    - 139.9.53.186:22122
  so-timeout: 10000
  thumb-image:
    height: 100
    width: 100

#fastdfs服务地址
fastdfspath: http://139.9.53.186:8080/